# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c1de752bde0b55ab33feadd08ebee115be6955f3155c635ffeb1a432b878976c1b61d4f905c1909dde18a9cd588e12d7dd951d90ab186463794af23750bdc19

test:
  secret_key_base: 9a7c7dd13eee207cfdd866f0595e52a16a475eeebbadf2e8ec0a680c298aac634b60998142e27e937c503487d0732304facc640ca52058787e9db7ea935dabb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
